/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AAlert: (typeof import("ant-design-vue/es"))["Alert"];
    AAutoComplete: (typeof import("ant-design-vue/es"))["AutoComplete"];
    ABadge: (typeof import("ant-design-vue/es"))["Badge"];
    AButton: (typeof import("ant-design-vue/es"))["Button"];
    ACard: (typeof import("ant-design-vue/es"))["Card"];
    ACheckbox: (typeof import("ant-design-vue/es"))["Checkbox"];
    ACol: (typeof import("ant-design-vue/es"))["Col"];
    ACollapse: (typeof import("ant-design-vue/es"))["Collapse"];
    ACollapsePanel: (typeof import("ant-design-vue/es"))["CollapsePanel"];
    AConfigProvider: (typeof import("ant-design-vue/es"))["ConfigProvider"];
    ADivider: (typeof import("ant-design-vue/es"))["Divider"];
    ADropdown: (typeof import("ant-design-vue/es"))["Dropdown"];
    AEmpty: (typeof import("ant-design-vue/es"))["Empty"];
    AForm: (typeof import("ant-design-vue/es"))["Form"];
    AFormItem: (typeof import("ant-design-vue/es"))["FormItem"];
    AInput: (typeof import("ant-design-vue/es"))["Input"];
    AInputGroup: (typeof import("ant-design-vue/es"))["InputGroup"];
    ALayout: (typeof import("ant-design-vue/es"))["Layout"];
    ALayoutContent: (typeof import("ant-design-vue/es"))["LayoutContent"];
    ALayoutFooter: (typeof import("ant-design-vue/es"))["LayoutFooter"];
    ALayoutHeader: (typeof import("ant-design-vue/es"))["LayoutHeader"];
    ALayoutSider: (typeof import("ant-design-vue/es"))["LayoutSider"];
    AMenu: (typeof import("ant-design-vue/es"))["Menu"];
    AMenuDivider: (typeof import("ant-design-vue/es"))["MenuDivider"];
    AMenuItem: (typeof import("ant-design-vue/es"))["MenuItem"];
    AModal: (typeof import("ant-design-vue/es"))["Modal"];
    ARadio: (typeof import("ant-design-vue/es"))["Radio"];
    ARadioGroup: (typeof import("ant-design-vue/es"))["RadioGroup"];
    ARow: (typeof import("ant-design-vue/es"))["Row"];
    ASelect: (typeof import("ant-design-vue/es"))["Select"];
    ASelectOption: (typeof import("ant-design-vue/es"))["SelectOption"];
    ASpin: (typeof import("ant-design-vue/es"))["Spin"];
    ASubMenu: (typeof import("ant-design-vue/es"))["SubMenu"];
    ATable: (typeof import("ant-design-vue/es"))["Table"];
    ATabPane: (typeof import("ant-design-vue/es"))["TabPane"];
    ATabs: (typeof import("ant-design-vue/es"))["Tabs"];
    ATag: (typeof import("ant-design-vue/es"))["Tag"];
    ATextarea: (typeof import("ant-design-vue/es"))["Textarea"];
    ATooltip: (typeof import("ant-design-vue/es"))["Tooltip"];
    ContextMenu: (typeof import("./src/components/common/ContextMenu.vue"))["default"];
    GlobalFooter: (typeof import("./src/components/GlobalFooter/index.vue"))["default"];
    GlobalHeader: (typeof import("./src/components/GlobalHeader/index.vue"))["default"];
    GlobalHeaderTab: (typeof import("./src/components/GlobalHeaderTab/index.vue"))["default"];
    HeaderSearch: (typeof import("./src/components/HeaderSearch/index.vue"))["default"];
    Markdown: (typeof import("./src/components/Markdown/index.vue"))["default"];
    MethodApi: (typeof import("./src/components/common/MethodApi.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SiderMenu: (typeof import("./src/components/SiderMenu/index.vue"))["default"];
    SubMenu: (typeof import("./src/components/SiderMenu/SubMenu.vue"))["default"];
    ThreeMenu: (typeof import("./src/components/SiderMenu/ThreeMenu.vue"))["default"];
    ThreeRoute: (typeof import("./src/components/SiderMenu/ThreeRoute.vue"))["default"];
    ThreeTitle: (typeof import("./src/components/SiderMenu/ThreeTitle.vue"))["default"];
  }
}
